ProwatchWebApp/Models/report.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProwatchWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int reportID { get; set; }
        public string taskName { get; set; }
        public string reportDescription { get; set; }
        public string createdBy { get; set; }
        public int userID { get; set; }
        public Nullable<int> projectStatusID { get; set; }
        public Nullable<int> taskID { get; set; }
    
        public virtual projectStatu projectStatu { get; set; }
        public virtual proUser proUser { get; set; }
        public virtual task task { get; set; }
    }
}

ProwatchWebApp/Controllers/reportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProwatchWebApp.Models;

namespace ProwatchWebApp.Controllers
{
    public class reportsController : Controller
    {
        private ProWatchEntities1 db = new ProWatchEntities1();

        // GET: reports
        public ActionResult Index()
        {
            var reports = db.reports.Include(r => r.projectStatu).Include(r => r.proUser).Include(r => r.task);
            return View(reports.ToList());
        }

        // GET: reports/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            report report = db.reports.Find(id);
            if (report == null)
            {
                return HttpNotFound();
            }
            return View(report);
        }

        // GET: reports/Create
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: reports/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
      //  [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "taskName,reportDescription")] report report)
        {
            if (ModelState.IsValid)
            {
				var user = User.Identity.Name;
				var userid = db.proUsers.Where(y => y.email == user).Select(y => y.userID).FirstOrDefault();
				report.userID = userid;
				var taskID = db.tasks.Where(y => y.taskName == report.taskName).Select(y => y.taskID).FirstOrDefault();
				report.taskID = taskID;
				db.reports.Add(report);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            
            return View(report);
        }

        // GET: reports/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            report report = db.reports.Find(id);
            if (report == null)
            {
                return HttpNotFound();
            }
            ViewBag.projectStatusID = new SelectList(db.projectStatus, "projectStatusID", "projectStatusName", report.projectStatusID);
            ViewBag.userID = new SelectList(db.proUsers, "userID", "firstname", report.userID);
            ViewBag.taskID = new SelectList(db.tasks, "taskID", "taskName", report.taskID);
            return View(report);
        }

        // POST: reports/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "reportID,taskName,reportDescription,createdBy,userID,projectStatusID,taskID")] report report)
        {
            if (ModelState.IsValid)
            {
                db.Entry(report).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.projectStatusID = new SelectList(db.projectStatus, "projectStatusID", "projectStatusName", report.projectStatusID);
            ViewBag.userID = new SelectList(db.proUsers, "userID", "firstname", report.userID);
            ViewBag.taskID = new SelectList(db.tasks, "taskID", "taskName", report.taskID);
            return View(report);
        }

        // GET: reports/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            report report = db.reports.Find(id);
            if (report == null)
            {
                return HttpNotFound();
            }
            return View(report);
        }

        // POST: reports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            report report = db.reports.Find(id);
            db.reports.Remove(report);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProwatchWebApp/Views/reports/Create.cshtml
@model ProwatchWebApp.Models.report

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_ProWatchLayout.cshtml";
}




		<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
			<div class="row">
				<ol class="breadcrumb">
					<li>
						<a href="index.html">
							<em class="fa fa-home"></em>
						</a>
					</li>
					<li class="active">Add Report</li>
				</ol>
			</div><!--/.row-->

			<div class="row">
				<div class="col-lg-12">
					<h1 class="page-header">Add Report</h1>
				</div>
			</div><!--/.row-->

			@using (Html.BeginForm("Create", "reports", FormMethod.Post, new { enctype = "multipart/form-data" }))
			{
				<div class="form-group col-md-5">
					<label>Task </label>
					<input class="form-control" type="text" name="taskName">
				</div>

				<div class="form-group col-md-5">
					<label>Report Description</label>
					<input class="form-control" type="text" name="reportDescription">
				</div>

				<div class="form-group col-md-8">
					<button id="ken" type="submit" class="btn btn-primary" style="float:left">Save</button>
				</div>
			}
		</div>
	

ProwatchWebApp/Views/reports/Delete.cshtml
@model ProwatchWebApp.Models.report

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_ProWatchLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>report</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.taskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.taskName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reportDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reportDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectStatu.projectStatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectStatu.projectStatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.proUser.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.proUser.firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.task.taskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.task.taskName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProwatchWebApp/Views/reports/Details.cshtml
@model ProwatchWebApp.Models.report

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_ProWatchLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>report</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.taskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.taskName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reportDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reportDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectStatu.projectStatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectStatu.projectStatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.proUser.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.proUser.firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.task.taskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.task.taskName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.reportID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProwatchWebApp/Views/reports/Edit.cshtml
@model ProwatchWebApp.Models.report

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_ProWatchLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>report</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.reportID)

        <div class="form-group">
            @Html.LabelFor(model => model.taskName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.taskName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.taskName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.reportDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.reportDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.reportDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.createdBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.createdBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.createdBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userID, "userID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("userID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.userID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.projectStatusID, "projectStatusID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("projectStatusID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.projectStatusID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.taskID, "taskID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("taskID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.taskID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProwatchWebApp/Views/reports/Index.cshtml
@model IEnumerable<ProwatchWebApp.Models.report>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ProWatchLayout.cshtml";
}


<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
	<div class="row">
		<ol class="breadcrumb">
			<li>
				<a href="index.html">
					<em class="fa fa-home"></em>
				</a>
			</li>
			<li class="active">General Report</li>
		</ol>
	</div><!--/.row-->

	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">General Report</h1>
		</div>
	</div><!--/.row-->

	<p>
		@Html.ActionLink("Create New", "Create")
	</p>
	<table class="table">
		<tr>

			<th>
				Report Description
			</th>

			<th>
				Status
			</th>
			<th>
				Name
			</th>
			<th>
				Task
			</th>

		</tr>

		@foreach (var item in Model)
		{
			<tr>

				<td>
					@Html.DisplayFor(modelItem => item.reportDescription)
				</td>

				<td>
					@Html.DisplayFor(modelItem => item.projectStatu.projectStatusName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.proUser.firstname)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.task.taskName)
				</td>

			</tr>
		}

	</table>
	</div>