ProwatchWebApp/Models/proUser.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProwatchWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proUser()
        {
            this.projects = new HashSet<project>();
            this.reports = new HashSet<report>();
            this.tasks = new HashSet<task>();
            this.UserProjects = new HashSet<UserProject>();
        }
    
        public int userID { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string phoneNumber { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report> reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task> tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProject> UserProjects { get; set; }
    }
}

ProwatchWebApp/Controllers/proUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProwatchWebApp.Models;
using System.Web.Security;

namespace ProwatchWebApp.Controllers
{
    public class proUsersController : Controller
    {
		private ProWatchEntities1 db = new ProWatchEntities1();

		// GET: proUsers
		public ActionResult Index()
        {
            return View(db.proUsers.ToList());
        }

        // GET: proUsers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            proUser proUser = db.proUsers.Find(id);
            if (proUser == null)
            {
                return HttpNotFound();
            }
            return View(proUser);
        }


        // GET: prouser/signIn
        public ActionResult signIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignIn(proUser user)

        {
            string firstname = db.proUsers.Where(y => y.email == user.email && y.password == user.password).Select(y => y.email).SingleOrDefault();
            if (firstname != null)
            {
                FormsAuthentication.SetAuthCookie(firstname, false);
                return RedirectToAction("Dashboard", "projects");               
            }
            TempData["Message"] = "Email or Password is Incorrect";
           
            return View();
           
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("SignIn");
        }


        // GET: proUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: proUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
       // [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "firstname,lastname,email,password,phoneNumber")] proUser proUser)
        {
            if (ModelState.IsValid)
            {
                DateTime dt = DateTime.Now.Date;
                proUser.dateCreated = dt;
                db.proUsers.Add(proUser);
                db.SaveChanges();
                FormsAuthentication.SetAuthCookie(proUser.firstname, false);
                return RedirectToAction("Dashboard", "projects");
            }

            return View(proUser);
        }

        // GET: proUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            proUser proUser = db.proUsers.Find(id);
            if (proUser == null)
            {
                return HttpNotFound();
            }
            return View(proUser);
        }

        // POST: proUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "userID,firstname,lastname,email,password,phoneNumber,dateCreated,dateModified")] proUser proUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(proUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(proUser);
        }

        // GET: proUsers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            proUser proUser = db.proUsers.Find(id);
            if (proUser == null)
            {
                return HttpNotFound();
            }
            return View(proUser);
        }

        // POST: proUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            proUser proUser = db.proUsers.Find(id);
            db.proUsers.Remove(proUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProwatchWebApp/Views/proUsers/Create.cshtml
@model ProwatchWebApp.Models.proUser

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>proUser</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateModified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateModified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateModified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProwatchWebApp/Views/proUsers/Delete.cshtml
@model ProwatchWebApp.Models.proUser

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>proUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateModified)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProwatchWebApp/Views/proUsers/Details.cshtml
@model ProwatchWebApp.Models.proUser

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>proUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateModified)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.userID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProwatchWebApp/Views/proUsers/Edit.cshtml
@model ProwatchWebApp.Models.proUser

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>proUser</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.userID)

        <div class="form-group">
            @Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateModified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateModified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateModified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProwatchWebApp/Views/proUsers/Index.cshtml
@model IEnumerable<ProwatchWebApp.Models.proUser>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dateModified)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.firstname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.lastname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.phoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dateCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dateModified)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.userID }) |
            @Html.ActionLink("Details", "Details", new { id=item.userID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.userID })
        </td>
    </tr>
}

</table>

ProwatchWebApp/Views/proUsers/SignIn.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login & Sign Up Form Concept</title>


    <link href="~/PorWatchFrontEnd/css/style.css" rel="stylesheet" />
    <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Open+Sans:400,300'>
    <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/icon?family=Material+Icons'>  
</head>
<body>
   
    <div class="cotn_principal">
        <img src="~/PorWatchFrontEnd/images/ProWatchLogo.png" width="150" height="100" />
        <div class="cont_centrar">
            <div class="cont_login">
                <div class="cont_info_log_sign_up">
                    <div class="col_md_login">
                        <div class="cont_ba_opcitiy">

                            <h2>LOGIN</h2>
                            <p>Already have an account? signin today</p>
                            <button class="btn_login" onclick="cambiar_login()">LOGIN</button>
                        </div>
                       
                    </div>
                    <div class="col_md_sign_up">
                        <div class="cont_ba_opcitiy">
                            <h2>SIGN UP</h2>

                            <p>Please register to be a user on Prowatch</p>
                            <button class="btn_sign_up" onclick="cambiar_sign_up()">SIGN UP</button>
                        </div>
                    </div>
                </div>

                <div class="cont_back_info">
                    <div class="cont_img_back_grey">
                        <img src="https://images.unsplash.com/42/U7Fc1sy5SCUDIu4tlJY3_NY_by_PhilippHenzler_philmotion.de.jpg?ixlib=rb-0.3.5&q=50&fm=jpg&crop=entropy&s=7686972873678f32efaf2cd79671673d" alt="" />
                    </div>

                </div>
                <div class="cont_forms">
                    <div class="cont_img_back_">
                        <img src="https://images.unsplash.com/42/U7Fc1sy5SCUDIu4tlJY3_NY_by_PhilippHenzler_philmotion.de.jpg?ixlib=rb-0.3.5&q=50&fm=jpg&crop=entropy&s=7686972873678f32efaf2cd79671673d" alt="" />
                    </div>
                   
                    @if (TempData["Message"] != null)
                    {
                        <div class="alert alert info" style="color:red">
                            @TempData["Message"].ToString()
                        </div>
                    }
                    @using (Html.BeginForm("signIn", "ProUsers", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                       
                        <div class="cont_form_login">
                            <a href="#" onclick="ocultar_login_sign_up()"><i class="material-icons">&#xE5C4;</i></a>
                            <h2>LOGIN</h2>
                            <input type="text" placeholder="Email" name="email" />
                            <input type="password" placeholder="Password" name="password"/>
                            <button class="btn_login" onclick="cambiar_login()">LOGIN</button>
                        </div>
                    }

@using (Html.BeginForm("Create", "proUsers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
                    <div class="cont_form_sign_up">
                        <a href="#" onclick="ocultar_login_sign_up()"><i class="material-icons">&#xE5C4;</i></a>
                        <h2>SIGN UP</h2>
                        <input type="text" placeholder="Email" name="email"/>
                        <input type="text" placeholder="Firstname" name="firstname" />
                        <input type="text" placeholder="Lastname" name="lastname" />
                        <input type="text" placeholder="Phone Number" name="phoneNumber" />
                        <input type="password" placeholder="Password" name="password" />
                       
                        <button class="btn_sign_up" onclick="cambiar_sign_up()">SIGN UP</button>
                    </div>
}
                </div>

            </div>
        </div>
    </div>

    <script src="~/PorWatchFrontEnd/js/index.js"></script>
</body>
</html>