ProwatchWebApp/Models/task.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProwatchWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public task()
        {
            this.reports = new HashSet<report>();
        }
    
        public int taskID { get; set; }
        public string taskName { get; set; }
        public string observedBy { get; set; }
        public System.DateTime deadlineDate { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
        public string createdBy { get; set; }
        public int userID { get; set; }
        public Nullable<int> projectStatusID { get; set; }
        public string assignTo { get; set; }
        public Nullable<int> projectID { get; set; }
    
        public virtual project project { get; set; }
        public virtual projectStatu projectStatu { get; set; }
        public virtual proUser proUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report> reports { get; set; }
    }
}

ProwatchWebApp/Controllers/tasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProwatchWebApp.Models;
using PagedList;
namespace ProwatchWebApp.Controllers
{
    public class tasksController : Controller
    {
		private ProWatchEntities1 db = new ProWatchEntities1();

		// GET: tasks
		public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var students = from s in db.tasks
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.taskName.Contains(searchString)
                                       || s.projectStatu.projectStatusName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    students = students.OrderByDescending(s => s.taskName);
                    break;
                case "Date":
                    students = students.OrderBy(s => s.projectStatu.projectStatusName);
                    break;
                case "date_desc":
                    students = students.OrderByDescending(s => s.projectStatu.projectStatusName);
                    break;
                default:  // Name ascending 
                    students = students.OrderBy(s => s.taskName);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(students.ToPagedList(pageNumber, pageSize));

        }

        // GET: tasks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            task task = db.tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // GET: tasks/Create
        public ActionResult Create()
        {
            var user = User.Identity.Name;
            ViewBag.Name = user;
            return View();
        }

        // POST: tasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
       // [ValidateAntiForgeryToken]
        public ActionResult Create(task task, string projectName)
        {
            if (ModelState.IsValid)
            {
                var user = User.Identity.Name;              
                DateTime dt = DateTime.Now.Date;
                var projectID = db.projects.Where(y => y.projectName == projectName).Select(y => y.projectID).FirstOrDefault();
                task.projectID = projectID;
                var userID = db.proUsers.Where(y => y.email == user).Select(y => y.userID).FirstOrDefault();
                task.userID = userID;
                task.dateCreated = dt;
                db.tasks.Add(task);
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            return View(task);
        }

        [HttpPost]
        public ActionResult AutoComplete(proUser user)
        {
            try
            {
                string term = user.email;
                if (term.Length > 0)
                {
                    return Json(db.proUsers.Where(x => x.email.StartsWith(term)).Select(y => y.email).ToArray(), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("No record", JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message + ex.StackTrace, JsonRequestBehavior.AllowGet);
            }
           
        }

        // GET: tasks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            task task = db.tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            ViewBag.projectStatusID = new SelectList(db.projectStatus, "projectStatusID", "projectStatusName", task.projectStatusID);
            ViewBag.userID = new SelectList(db.proUsers, "userID", "firstname", task.userID);
            return View(task);
        }

        // POST: tasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "taskID,taskName,observedBy,deadlineDate,dateCreated,dateModified,createdBy,userID,projectStatusID,assignTo")] task task)
        {
            if (ModelState.IsValid)
            {
                db.Entry(task).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.projectStatusID = new SelectList(db.projectStatus, "projectStatusID", "projectStatusName", task.projectStatusID);
            ViewBag.userID = new SelectList(db.proUsers, "userID", "firstname", task.userID);
            return View(task);
        }

        // GET: tasks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            task task = db.tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            task task = db.tasks.Find(id);
            db.tasks.Remove(task);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProwatchWebApp/Views/tasks/Create.cshtml
@model ProwatchWebApp.Models.task

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_ProWatchLayout.cshtml";
}

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
        <ol class="breadcrumb">
            <li>
                <a href="index.html">
                    <em class="fa fa-home"></em>
                </a>
            </li>
            <li class="active">Create Task</li>
        </ol>
    </div><!--/.row-->

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">New Task</h1>
        </div>
    </div><!--/.row-->

    @using (Html.BeginForm("Create", "tasks", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-group col-md-5">
            <label>Task </label>
            <input class="form-control" type="text" name="taskName">
        </div>

        <div class="form-group col-md-5">
            <label>Assign To</label>
            <input class="form-control" type="text" name="assignTo" id="email">
        </div>

        <div class="form-group col-md-5">
            <label>Deadline</label>
            <input class="form-control" type="date" name="deadlineDate">
        </div>

        <div class="form-group col-md-5">
            <label>Assign By</label>
            <input class="form-control" type="text" name="createdBy" value="@ViewBag.Name">
        </div>


        <div class="form-group col-md-5">
            <label>Supervise By</label>
            <input class="form-control" type="text" name="observedBy">
        </div>

        <div class="form-group col-md-5">
            <label>Project Name </label>
            <input class="form-control" type="text" name="projectName">
        </div>
        <div class="form-group col-md-8">
            <button id="ken" type="submit" class="btn btn-primary" style="float:left">Save</button>
        </div>
    }
</div>	<!--/.main-->

ProwatchWebApp/Views/tasks/Delete.cshtml
@model ProwatchWebApp.Models.task

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_ProWatchLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>task</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.taskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.taskName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.observedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.observedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deadlineDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deadlineDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateModified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.assignTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.assignTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectStatu.projectStatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectStatu.projectStatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.proUser.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.proUser.firstname)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProwatchWebApp/Views/tasks/Details.cshtml
@model ProwatchWebApp.Models.task

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_ProWatchLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>task</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.taskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.taskName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.observedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.observedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deadlineDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deadlineDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateModified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.assignTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.assignTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectStatu.projectStatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectStatu.projectStatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.proUser.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.proUser.firstname)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.taskID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProwatchWebApp/Views/tasks/Edit.cshtml
@model ProwatchWebApp.Models.task

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_ProWatchLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>task</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.taskID)

        <div class="form-group">
            @Html.LabelFor(model => model.taskName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.taskName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.taskName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.observedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.observedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.observedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deadlineDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deadlineDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deadlineDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateModified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateModified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateModified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.createdBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.createdBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.createdBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userID, "userID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("userID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.userID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.projectStatusID, "projectStatusID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("projectStatusID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.projectStatusID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.assignTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.assignTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.assignTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProwatchWebApp/Views/tasks/Index.cshtml
@model PagedList.IPagedList<ProwatchWebApp.Models.task>
@using PagedList.Mvc;
@{
    Layout = "~/Views/Shared/_ProWatchLayout.cshtml";
}

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

    @using (Html.BeginForm("Index", "projects", FormMethod.Get))
    {
        <p>
            Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" />
        </p>
    }
    <table id="example1" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>@Html.ActionLink("Task", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })</th>
                <th>@Html.ActionLink("Status", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })</th>
                <th>Assigned To</th>
                <th>Update</th>
            </tr>
        </thead>
        @foreach (var item in Model)
            {
            <tbody>
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.taskName)
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.projectStatu.projectStatusName)</td>
                    <td>@Html.DisplayFor(modelItem => item.assignTo)</td>
                    <td>
                        @Html.ActionLink("Edits", "Edit", new { id = item.taskID }) |
                        @Html.ActionLink("Detail", "Details", new { id = item.taskID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.taskID })
                    </td>
                </tr>
            </tbody>
        }
        <tfoot>
            <tr>

            </tr>
        </tfoot>
    </table>
 
</div>